### ISSUE TITLE
Refining the SMTP validation firewall port has email port open

### ISSUE THREAD

**Issue by cognoquest** [lamw/ghettoVCB#161]
Thank your all and especially @lamw  for the script and its support. Please do not take the following feedback as criticism,it is not. This script is wonderful.

When I started using the script I got stumped by the outbound SMTP firewall rule being blocked. Now I am sure I am not the first one but the difficulty that I had with my ESXI configuration is that the check in the script for the firewall rule validation failed because of the following:

`[root@esxi03:~] /sbin/esxcli network firewall ruleset rule list | grep "25"`
> pvrdma                    Outbound   TCP       Dst             28250     28761
pvrdma                    Inbound    TCP       Dst             28250     28761

I got a fall positive from the check. May I suggest that the check be changed for the following: 
`/sbin/esxcli network firewall ruleset rule list | grep " ${EMAIL_SERVER_PORT} " > /dev/null 2>&1`
I added a space before and after: ${EMAIL_SERVER_PORT}

**Comment by lamw** [comment]
Good catch. I've just fixed it with the following:

```
/sbin/esxcli network firewall ruleset rule list | | awk '{print $5}' | grep "^${EMAIL_SERVER_PORT}" > /dev/null 2>&1
```

**Comment by cognoquest** [comment]
Hello @lamw 
You mean:
`/sbin/esxcli network firewall ruleset rule list | awk '{print $5}' | grep "^${EMAIL_SERVER_PORT}" > /dev/null 2>&1`

I am still having the same problem? 

`/sbin/esxcli network firewall ruleset rule list | awk '{print $5}' | grep "25"`
>
28250
28250

**Comment by lamw** [comment]
You missed `^` symbol, which says looking for anything that starts with 25 ... actually I should do "^25$" so that 25555 wouldn't pass

**Comment by cognoquest** [comment]
Oops thanks many times
