### ISSUE TITLE
Mouting NFS Datastore failing on ESXi 7.0 Update 1 because missing version reference in line 897

### ISSUE THREAD

**Issue by ptgob** [lamw/ghettoVCB#206]
On October 10th, an update was made to support ESXi 7.0 Update 1. But the modification of line 897 was not updates to reference version 7.0.1. The result is NFS Datastore is failing to mount and the backup failed.
Correction is proposed here #205

**Comment by lamw** [comment]
Resolved

**Comment by kubedzero** [comment]
Just to be clear, https://github.com/lamw/ghettoVCB/archive/latest.zip (currently labeled as `ghettoVCB - 2020_10_23`) does NOT fix this issue. Unfortunately, line 897 within its source code still only has 7.0.0. I was confused for a while but upon downloading the repo rather than the release, I was able to mount NFS correctly.

**Comment by discofris** [comment]
> 
> 
> Just to be clear, https://github.com/lamw/ghettoVCB/archive/latest.zip (currently labeled as `ghettoVCB - 2020_10_23`) does NOT fix this issue. Unfortunately, line 897 within its source code still only has 7.0.0. I was confused for a while but upon downloading the repo rather than the release, I was able to mount NFS correctly.

So you made your own VIB?

**Comment by kubedzero** [comment]
> So you made your own VIB?

Nope, no need for a VIB. I just have the raw .sh files on my Datastore alongside my VM files, and I call it from there. It never gets installed to the bootbank or location with all the other VIB and system files,  but  I've not yet found a need for it to be there. That said, I'm not doing anything fancy with SANs or remote Datastores, I have one ESXi host and an SSD inside as a datastore, with a USB providing the ESXI boot files. 

```
[root@esxi:~] ls -aRhl /vmfs/volumes/970PRO/ghettoVCB/
/vmfs/volumes/970PRO/ghettoVCB/:
total 3264
drwxr-xr-x    1 root     root       76.0K Nov 14 07:02 .
drwxr-xr-t    1 root     root       84.0K Dec 19 08:16 ..
-rw-r--r--    1 root     root        2.7K May 24  2020 README.md
-rwxr-xr-x    1 root     root       17.2K Nov 14 07:01 ghettoVCB-restore.sh
-rw-r--r--    1 root     root      322.0K Dec  3 08:58 ghettoVCB.log
-rwxr-xr-x    1 root     root       70.5K Nov 14 07:01 ghettoVCB.sh
-rw-r--r--    1 root     root          52 Nov 14 06:24 kzExcludedVms
-rwxr-xr-x    1 root     root         193 Feb 15  2020 kzGVCB.sh
-rw-r--r--    1 root     root         815 Nov 14 06:40 kzGhettoVCB.conf
-rw-r--r--    1 root     root          79 Jan 15  2020 kzVms

[root@esxi:~] tail -6 /etc/rc.local.d/local.sh
/bin/echo "15 8 3 * * /vmfs/volumes/970PRO/ghettoVCB/kzGVCB.sh" >> /var/spool/cron/crontabs/root
crond



exit 0
```
